### ISSUE TITLE
Use structs rather than maps for the metadata

### ISSUE THREAD

**Issue by jacklund** [jacklund/kafka_ex#11]
Right now, we're using nested maps as the data structure for the metadata we get back, which directly parallels the data being returned from Kafka. We would like to, instead, return structs for the metadata, the topics, and the partitions.

**Comment by bjhaid** [comment]
closed with: https://github.com/jacklund/kafka_ex/commit/722a7768fc32a3bead68bd5df5a8dd68d7c43523
