### ISSUE TITLE
Add Consumer Groups

### ISSUE THREAD

**Issue by bjhaid** [jacklund/kafka_ex#14]

**Comment by jacklund** [comment]
:+1:

**Comment by dantswain** [comment]
Have you guys had any chance to look at implementing this?  I'm interested in seeing it get done and might be able to help.

**Comment by bjhaid** [comment]
@dantswain We have a WIP branch, we would work on it tomorrow and possibly check back this weekend

**Comment by dantswain** [comment]
Is the branch published?  I'd be happy to review.

**Comment by bjhaid** [comment]
@dantswain https://github.com/bjhaid/kafka_ex/tree/consumer_group

**Comment by bjhaid** [comment]
@dantswain https://hex.pm/packages/kafka_ex/0.1.0
http://hexdocs.pm/kafka_ex/0.1.0/

**Comment by dantswain** [comment]
:+1:!
